name: Auto test new changes 
on:
  pull_request:
    branches:
      - main 
      

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14.x" 

      - name: Install dependencies
        run: |
          npm ci

      - name: Run tests
        continue-on-error: false
        working-directory: "./test"
        run: |
          npx playwright install
          HOME=/root npx playwright test

